# roles/hosts/tasks/main.yml
---

- name: Install custom hosts file
  template:
    src: etc_hosts.j2
    dest: "{{ hosts_file }}"
    owner: root
    group: root
    mode: 0644
    backup: "{{ host_file_backup }}"
  tags: hosts
